namespace Tedd.WildcardMatchTests
{
    public class TestData
    {
        public static string _lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed aliquet condimentum risus. Maecenas tempus eget diam posuere volutpat. Pellentesque ut dignissim libero. Quisque justo odio, tempor sit amet hendrerit vitae, venenatis vel orci. Vestibulum at orci est. Cras id malesuada metus. Mauris varius odio in diam molestie venenatis. Morbi ac laoreet massa. Ut sollicitudin iaculis turpis ut cursus. Nulla ac sem vitae justo egestas ultrices vitae ut sapien. Sed et sem id ipsum fringilla volutpat. Pellentesque sed urna erat. Fusce vehicula eleifend leo id dapibus.\r\n\r\n"
                                      + "Praesent nisi turpis, pulvinar a velit ac, tincidunt aliquam nisl.Fusce metus dui, blandit quis ultricies vel, ullamcorper a eros.In finibus sed quam vel laoreet. Mauris et lorem a ligula fringilla lacinia.Quisque auctor risus at urna interdum, ut laoreet leo tincidunt. Ut pulvinar tempus mi sit amet auctor.Vestibulum neque arcu, finibus in lobortis a, accumsan in nunc.Nullam vel velit vel libero tincidunt volutpat sit amet sit amet sapien. Sed tristique, urna ut feugiat vehicula, felis dui venenatis nulla, vitae luctus libero dolor vel augue. Quisque sit amet mi velit.Fusce posuere sem in dolor accumsan, id dictum dui lobortis. Ut ornare tortor vel dolor gravida lacinia tincidunt vulputate diam. Fusce egestas diam non ante condimentum, sit amet cursus mi consectetur.\r\n\r\n"
                                      + "Nulla accumsan blandit ipsum, at viverra nisi venenatis sed.Fusce eget velit quis justo accumsan suscipit mattis luctus dui. Cras pulvinar pulvinar nulla vel hendrerit. Donec fermentum ultricies mi at faucibus. Vestibulum quis odio nec magna ultrices venenatis.Aliquam cursus nisi ac felis luctus tincidunt.Praesent finibus vulputate aliquet. Etiam ultricies dolor vitae ornare imperdiet. Mauris mollis turpis neque, eget pulvinar elit feugiat nec.\r\n\r\n"
                                      + "Proin quam turpis, posuere ac porta id, placerat quis nulla.Aliquam erat volutpat.Curabitur faucibus semper congue. Cras auctor elit vel leo molestie eleifend.Ut neque turpis, ultricies at orci sit amet, cursus iaculis nisl.Praesent pulvinar sit amet lorem ut maximus.Fusce rhoncus sed odio a laoreet. Morbi egestas rhoncus augue, ut aliquam erat aliquet sodales.Proin posuere vel enim a efficitur. Ut posuere malesuada enim, id lacinia felis pellentesque vel.Donec pharetra augue at erat efficitur, a pulvinar nunc varius. Suspendisse pharetra pharetra mi a efficitur. Ut turpis lectus, ullamcorper at velit id, aliquam vulputate purus.Lorem ipsum dolor sit amet, consectetur adipiscing elit.Vestibulum ac lacus sed neque pulvinar interdum vel ut erat. Duis imperdiet eget arcu sed aliquet.\r\n\r\n"
                                      + "Aliquam augue augue, cursus non porttitor vitae, ultrices et lectus.Duis tempor dapibus erat eu vehicula. Curabitur laoreet pellentesque neque a vestibulum. Maecenas sodales ex pulvinar viverra porttitor. Vivamus posuere, mi ac scelerisque imperdiet, risus nunc venenatis ligula, nec luctus nisl felis ac neque. Cras ultrices vel enim quis rhoncus. Phasellus fringilla vitae enim et pretium. Etiam eget dictum lacus. Sed laoreet in felis ac tincidunt.Vivamus vel mollis lorem. Proin quis arcu cursus, fermentum nulla eu, tempor nunc. Duis consequat vestibulum gravida.\r\n";

        public static string loremAdv = "*!*?*" + _lorem + "\\*1??*\\";
    }
}